#!/usr/bin/env bash
#
# build-template.sh — Bake an Ubuntu VM into a Proxmox-ready template.
#
# Run as root on a freshly installed Ubuntu Server VM. The VM will be
# shut down at the end. Then on the Proxmox host, run:
#   qm template <vmid>
#
# The firstboot wizard (firstboot-config.sh) is embedded at build time
# via make build — do not edit this file's FIRSTBOOT_EOF block directly.
# Edit scripts/firstboot-config.sh instead.
#

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Run as root." >&2
  exit 1
fi

log() { printf '\n\033[1;36m[+] %s\033[0m\n' "$*"; }

# --------------------------------------------------------------------------
log "Updating apt and upgrading packages"
# --------------------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y upgrade

# --------------------------------------------------------------------------
log "Installing base packages"
# --------------------------------------------------------------------------
apt-get -y install \
  qemu-guest-agent \
  cloud-init \
  openssh-server \
  ufw \
  chrony \
  unattended-upgrades \
  curl \
  wget \
  vim \
  htop \
  net-tools \
  dnsutils \
  tmux \
  git \
  jq \
  ca-certificates \
  gnupg

systemctl enable qemu-guest-agent
systemctl enable ssh
systemctl enable chrony

# --------------------------------------------------------------------------
log "Adding Charm apt repo and installing gum (for firstboot TUI)"
# --------------------------------------------------------------------------
mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key \
  | gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" \
  >/etc/apt/sources.list.d/charm.list
apt-get update
apt-get install -y gum

# --------------------------------------------------------------------------
log "Setting timezone to Australia/Sydney"
# --------------------------------------------------------------------------
# Default timezone. Operators change this in the firstboot wizard, or fork
# the script and set a different IANA zone name here.
timedatectl set-timezone Australia/Sydney

# --------------------------------------------------------------------------
log "Hardening SSH (root login disabled; password auth left for firstboot wizard)"
# --------------------------------------------------------------------------
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/^#*PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config

# --------------------------------------------------------------------------
log "Configuring UFW (allow 22/tcp only)"
# --------------------------------------------------------------------------
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw --force enable

# --------------------------------------------------------------------------
log "Capping systemd-networkd-wait-online timeout"
# --------------------------------------------------------------------------
# Without this the service waits indefinitely on boot, causing a >1 minute
# hang on every clone. 10 s is enough for the primary NIC to come up.
mkdir -p /etc/systemd/system/systemd-networkd-wait-online.service.d
cat >/etc/systemd/system/systemd-networkd-wait-online.service.d/timeout.conf <<'EOF'
[Service]
TimeoutStartSec=10
EOF

# --------------------------------------------------------------------------
log "Enabling unattended security upgrades"
# --------------------------------------------------------------------------
dpkg-reconfigure -plow -fnoninteractive unattended-upgrades || true

# --------------------------------------------------------------------------
log "Installing Node.js 24 LTS (NodeSource) for Claude Code"
# --------------------------------------------------------------------------
# Pinned to Node.js 24 LTS (current LTS as of 2025). When Node.js 26 LTS
# ships (expected 2026-10), change setup_24.x to setup_26.x here and in
# docs/customisation.md. Verify the NodeSource URL hasn't changed first —
# see docs/troubleshooting.md#nodesource-url-changes.
curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
apt-get install -y nodejs

# --------------------------------------------------------------------------
log "Installing Claude Code globally"
# --------------------------------------------------------------------------
npm install -g @anthropic-ai/claude-code
echo "Claude Code installed at: $(which claude)"
claude --version || true

# --------------------------------------------------------------------------
log "Installing firstboot-config.sh into /usr/local/sbin"
# --------------------------------------------------------------------------
cat >/usr/local/sbin/firstboot-config.sh <<'FIRSTBOOT_EOF'
__FIRSTBOOT_PLACEHOLDER__
FIRSTBOOT_EOF
chmod +x /usr/local/sbin/firstboot-config.sh

# --------------------------------------------------------------------------
log "Wiring firstboot-config.sh to run on first interactive login"
# --------------------------------------------------------------------------
cat >/etc/profile.d/zz-firstboot.sh <<'PROFILE_EOF'
# Run firstboot config on first interactive SSH login.
# Skips for root and non-interactive shells.
if [ -t 0 ] && [ -z "${FIRSTBOOT_DONE:-}" ] && [ ! -f /var/lib/firstboot-done ]; then
  if [ "$(id -u)" -ne 0 ] && [ -x /usr/local/sbin/firstboot-config.sh ]; then
    sudo /usr/local/sbin/firstboot-config.sh || true
  fi
fi
PROFILE_EOF
chmod 0644 /etc/profile.d/zz-firstboot.sh

# Narrowly-scoped sudoers: this script only, no password.
cat >/etc/sudoers.d/90-firstboot <<'SUDOERS_EOF'
%sudo ALL=(root) NOPASSWD: /usr/local/sbin/firstboot-config.sh
SUDOERS_EOF
chmod 0440 /etc/sudoers.d/90-firstboot

# --------------------------------------------------------------------------
log "Cleaning up for templating"
# --------------------------------------------------------------------------

truncate -s 0 /etc/machine-id
rm -f /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id

rm -f /etc/ssh/ssh_host_*

cloud-init clean --logs --seed || true

apt-get clean
apt-get autoremove -y

journalctl --rotate || true
journalctl --vacuum-time=1s || true

find /var/log -type f -exec truncate -s 0 {} \; || true

history -c || true
rm -f /root/.bash_history
unset HISTFILE

log "Template prep complete."
echo
echo "Next steps on the Proxmox host:"
echo "  qm set <vmid> --agent enabled=1"
echo "  qm set <vmid> --ide2 local-lvm:cloudinit"
echo "  qm set <vmid> --serial0 socket --vga serial0"
echo "  qm set <vmid> --boot order=scsi0"
echo "  qm template <vmid>"
echo
echo "Shutting down in 5 seconds — press Ctrl-C to cancel."
sleep 5
shutdown -h now
